export function sourceColor(source: string) {
  if (source === 'rule') return '#B7791A'
  if (source === 'groq') return '#2E8B57'
  return '#2E7DB8'
}

export default function AiSourceBadge({ source, detailed }: { source?: string; detailed?: boolean }) {
  const s = (source || 'rule').toLowerCase()
  if (s === 'rule') {
    return (
      <span
        title="Rule-based fallback: the AI model was offline or returned no usable result, so this entry was scored by deterministic keyword/emotion rules. Treat as degraded, not low-risk."
        style={{
          background: '#B7791A22', color: '#B7791A', fontSize: '0.6rem', padding: '2px 7px',
          borderRadius: '3px', fontWeight: 700, border: '1px solid #B7791A55',
        }}
      >
        {detailed ? '⚠ RULE-SCORED — MODEL OFFLINE' : '⚠ RULE'}
      </span>
    )
  }
  return (
    <span
      title={`Generated by ${s}`}
      style={{
        background: `${sourceColor(s)}22`, color: sourceColor(s), fontSize: '0.6rem',
        padding: '2px 7px', borderRadius: '3px', fontWeight: 600, border: `1px solid ${sourceColor(s)}44`,
      }}
    >
      {s.toUpperCase()}
    </span>
  )
}
