"""initial schema with soft deletes and refresh tokens

Revision ID: a059d07dd9b6
Revises: 
Create Date: 2026-07-22 19:43:36.910146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a059d07dd9b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('emotion_probabilities', sa.Text(), nullable=True))
    op.add_column('journal_entries', sa.Column('created_at', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('deleted_at', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('deleted_by', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('updated_at', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('deleted_at', sa.String(), nullable=True))
    op.add_column('patient_profiles', sa.Column('deleted_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'deleted_by')
    op.drop_column('patient_profiles', 'deleted_at')
    op.drop_column('patient_profiles', 'updated_at')
    op.drop_column('journal_entries', 'deleted_by')
    op.drop_column('journal_entries', 'deleted_at')
    op.drop_column('journal_entries', 'updated_at')
    op.drop_column('journal_entries', 'created_at')
    op.drop_column('journal_entries', 'emotion_probabilities')
    # ### end Alembic commands ###
