"""initial schema with soft deletes and refresh tokens

Revision ID: a059d07dd9b6
Revises:
Create Date: 2026-07-22 19:43:36.910146

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a059d07dd9b6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _columns(table: str) -> set[str]:
    from sqlalchemy import inspect

    return {c["name"] for c in inspect(op.get_bind()).get_columns(table)}


def _add_column_if_missing(table: str, column: str, coltype, **kw) -> None:
    if column not in _columns(table):
        op.add_column(table, sa.Column(column, coltype, **kw))


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    _add_column_if_missing("journal_entries", "emotion_probabilities", sa.Text(), nullable=True)
    _add_column_if_missing("journal_entries", "created_at", sa.String(), nullable=True)
    _add_column_if_missing("journal_entries", "updated_at", sa.String(), nullable=True)
    _add_column_if_missing("journal_entries", "deleted_at", sa.String(), nullable=True)
    _add_column_if_missing("journal_entries", "deleted_by", sa.String(), nullable=True)
    _add_column_if_missing("patient_profiles", "updated_at", sa.String(), nullable=True)
    _add_column_if_missing("patient_profiles", "deleted_at", sa.String(), nullable=True)
    _add_column_if_missing("patient_profiles", "deleted_by", sa.String(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    for table, column in [
        ("patient_profiles", "deleted_by"),
        ("patient_profiles", "deleted_at"),
        ("patient_profiles", "updated_at"),
        ("journal_entries", "deleted_by"),
        ("journal_entries", "deleted_at"),
        ("journal_entries", "updated_at"),
        ("journal_entries", "created_at"),
        ("journal_entries", "emotion_probabilities"),
    ]:
        if column in _columns(table):
            op.drop_column(table, column)
    # ### end Alembic commands ###
